## Data Pre-processing and Exploratory Data Analysis

In [1]:
##import the libraries
import numpy as np
import pandas as pd

#Load the Data
patient_data=pd.read_csv("Health_Data.csv")

##use the head function to get a glimpse data
patient_data.head()

,Patient_id,Age,Admission_type,PreExistingDisease,PreviousSurgery,Gender,Smoker,Homeless,DaysinHospital,Readmitted
0,1,33,Urgent,Y,0,M,1,0,1,0
1,2,34,Emergency,N,0,M,1,0,22,0
2,3,88,Trauma,Y,1,M,1,1,100,1
3,4,56,Elective,Y,0,M,1,0,2,0
4,5,45,Trauma,Y,0,M,1,0,34,0

In [2]:
##Summary of Numerical Data
patient_data.describe()

,Patient_id,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,Readmitted
count,357.00000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000
mean,179.00000,42.574230,0.341737,0.596639,0.378151,43.182073,0.193277
std,103.20126,29.274624,0.474957,0.491261,0.485606,47.362609,0.395423
min,1.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,90.00000,14.000000,0.000000,0.000000,0.000000,12.000000,0.000000
50%,179.00000,35.000000,0.000000,1.000000,0.000000,32.000000,0.000000
75%,268.00000,67.000000,1.000000,1.000000,1.000000,55.000000,0.000000
max,357.00000,96.000000,1.000000,1.000000,1.000000,352.000000,1.000000

In [3]:
##Summary of Categorical Data
patient_data.describe(include=['object'])

       Admission_type PreExistingDisease Gender
count             357                357    357
unique              5                  2      2
top            Urgent                  N      F
freq              131                228    186

In [4]:
mydata=pd.read_csv("Health_Data.csv")
X=mydata.iloc[:,1:9]
y=mydata.iloc[:,9]

In [5]:
X.head()

,Age,Admission_type,PreExistingDisease,PreviousSurgery,Gender,Smoker,Homeless,DaysinHospital
0,33,Urgent,Y,0,M,1,0,1
1,34,Emergency,N,0,M,1,0,22
2,88,Trauma,Y,1,M,1,1,100
3,56,Elective,Y,0,M,1,0,2
4,45,Trauma,Y,0,M,1,0,34

In [6]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Readmitted, dtype: int64

In [7]:
##New Admission type
A_type=pd.get_dummies(X.iloc[:,1],drop_first=True,prefix='Atype')

##New Gender 
New_gender=pd.get_dummies(X.iloc[:,4],drop_first=True,prefix='Gender')

##New Pre Existing Disease Variable
Pre_exdis=pd.get_dummies(X.iloc[:,2],drop_first=True,prefix='PreExistDis')

In [8]:
## Drop the original categorical columns
X.drop(['Admission_type','PreExistingDisease','Gender'],axis=1,inplace=True)

##Concat the new transformed data to X dataframe
X=pd.concat([X,A_type,New_gender,Pre_exdis],axis=1)

In [9]:
X.head()

,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,Atype_Emergency,Atype_Newborn,Atype_Trauma,Atype_Urgent,Gender_M,PreExistDis_Y
0,33,0,1,0,1,0,0,0,1,1,1
1,34,0,1,0,22,1,0,0,0,1,0
2,88,1,1,1,100,0,0,1,0,1,1
3,56,0,1,0,2,0,0,0,0,1,1
4,45,0,1,0,34,0,0,1,0,1,1

In [10]:
##Split The Data into Train and Test
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(X, y, test_size=0.30, random_state=110)

In [11]:
##Initialize StandardScaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#Transform the training data
xtrain=sc.fit_transform(xtrain)
xtrain=pd.DataFrame(xtrain,columns=xtest.columns)

#Transform the testing data
xtest=sc.transform(xtest)
xtest=pd.DataFrame(xtest,columns=xtrain.columns)

C:\Users\Ritesh\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Ritesh\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Ritesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  # Remove the CWD from sys.path while we load stuff.

In [12]:
#Convert DataFrame to Numpy array

x_train=xtrain.values
x_test=xtest.values
y_train=ytrain.values
y_test=ytest.values

In [13]:
xtrain.head()

,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,Atype_Emergency,Atype_Newborn,Atype_Trauma,Atype_Urgent,Gender_M,PreExistDis_Y
0,1.415411,1.340803,0.792118,1.210515,1.883715,-0.363068,-0.303488,1.835326,-0.739313,-0.911527,1.306339
1,1.583479,1.340803,0.792118,1.210515,1.069799,-0.363068,-0.303488,1.835326,-0.739313,-0.911527,1.306339
2,0.675914,-0.745822,0.792118,1.210515,-0.453684,-0.363068,-0.303488,-0.544862,1.352607,1.097060,-0.765498
3,0.306166,-0.745822,-1.262438,-0.826095,-0.244988,2.754307,-0.303488,-0.544862,-0.739313,-0.911527,-0.765498
4,-1.071987,-0.745822,0.792118,-0.826095,-0.912816,-0.363068,-0.303488,-0.544862,-0.739313,1.097060,-0.765498

## Train a Neural Network and find its accuracy

In [14]:
##Import the relevant Keras libraries
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.

In [15]:
##Initiate the Model with Sequential Class
model=Sequential()

In [16]:
## Add the 1st dense layer and Dropout Layer
model.add(Dense(units=6,activation='relu',kernel_initializer='uniform',input_dim=11))
model.add(Dropout(rate=0.3))

WARNING:tensorflow:From C:\Users\Ritesh\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Ritesh\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

In [17]:
##Add the 2nd dense Layer and Dropout Layer
model.add(Dense(units=6,activation='relu',kernel_initializer='uniform'))
model.add(Dropout(rate=0.3))

In [18]:
##Add Output Dense Layer
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='uniform'))

In [19]:
#Compile the Model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
#Fit the Model
model.fit(x_train,y_train,epochs=200,batch_size=20,)

WARNING:tensorflow:From C:\Users\Ritesh\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/200
249/249 [==============================] - 0s 1ms/step - loss: 0.6914 - acc: 0.7711
Epoch 2/200
249/249 [==============================] - 0s 72us/step - loss: 0.6873 - acc: 0.7912
Epoch 3/200
249/249 [==============================] - 0s 64us/step - loss: 0.6821 - acc: 0.7912
Epoch 4/200
249/249 [==============================] - 0s 64us/step - loss: 0.6766 - acc: 0.7912
Epoch 5/200
249/249 [==============================] - 0s 72us/step - loss: 0.6683 - acc: 0.7912
Epoch 6/200
249/249 [==============================] - 0s 64us/step - loss: 0.6604 - acc: 0.7912
Epoch 7/200
249/249 [==============================] - 0s 60us/step - loss: 0.6483 - acc: 0.7912
Epoch 8/200
249/249 [==============================] - 0s 52us/step - loss: 0.6342 - acc: 0.7912
Epoch 9/200
249/249 [==============================] - 0s 52us/step - loss: 0.6139 - acc: 0.7912
Epoch 10/200
249/249 [==============================] - 0s 56us/step - loss: 0.5967 - acc: 0.7912
Epoch 11/200
249/249 [==============================] - 0s 68us/step - loss: 0.5747 - acc: 0.7912
Epoch 12/200
249/249 [==============================] - 0s 68us/step - loss: 0.5572 - acc: 0.7912
Epoch 13/200
249/249 [==============================] - 0s 72us/step - loss: 0.5362 - acc: 0.7912
Epoch 14/200
249/249 [==============================] - 0s 84us/step - loss: 0.5116 - acc: 0.7912
Epoch 15/200
249/249 [==============================] - 0s 64us/step - loss: 0.4988 - acc: 0.7912
Epoch 16/200
249/249 [==============================] - 0s 72us/step - loss: 0.4663 - acc: 0.7912
Epoch 17/200
249/249 [==============================] - 0s 52us/step - loss: 0.4574 - acc: 0.7912
Epoch 18/200
249/249 [==============================] - 0s 56us/step - loss: 0.4438 - acc: 0.7912
Epoch 19/200
249/249 [==============================] - 0s 64us/step - loss: 0.4238 - acc: 0.7912
Epoch 20/200
249/249 [==============================] - 0s 64us/step - loss: 0.4138 - acc: 0.7952
Epoch 21/200
249/249 [==============================] - 0s 64us/step - loss: 0.4239 - acc: 0.8072
Epoch 22/200
249/249 [==============================] - 0s 52us/step - loss: 0.4028 - acc: 0.8233
Epoch 23/200
249/249 [==============================] - 0s 72us/step - loss: 0.4024 - acc: 0.8514
Epoch 24/200
249/249 [==============================] - 0s 68us/step - loss: 0.3902 - acc: 0.8273
Epoch 25/200
249/249 [==============================] - 0s 108us/step - loss: 0.3728 - acc: 0.8474
Epoch 26/200
249/249 [==============================] - 0s 60us/step - loss: 0.3912 - acc: 0.8112
Epoch 27/200
249/249 [==============================] - 0s 76us/step - loss: 0.3840 - acc: 0.8514
Epoch 28/200
249/249 [==============================] - 0s 68us/step - loss: 0.3860 - acc: 0.8514
Epoch 29/200
249/249 [==============================] - 0s 68us/step - loss: 0.3657 - acc: 0.8474
Epoch 30/200
249/249 [==============================] - 0s 68us/step - loss: 0.3964 - acc: 0.8394
Epoch 31/200
249/249 [==============================] - 0s 80us/step - loss: 0.3672 - acc: 0.8554
Epoch 32/200
249/249 [==============================] - 0s 68us/step - loss: 0.3683 - acc: 0.8394
Epoch 33/200
249/249 [==============================] - 0s 84us/step - loss: 0.3552 - acc: 0.8313
Epoch 34/200
249/249 [==============================] - 0s 68us/step - loss: 0.3452 - acc: 0.8514
Epoch 35/200
249/249 [==============================] - 0s 72us/step - loss: 0.3500 - acc: 0.8313
Epoch 36/200
249/249 [==============================] - 0s 88us/step - loss: 0.3542 - acc: 0.8394
Epoch 37/200
249/249 [==============================] - 0s 80us/step - loss: 0.3719 - acc: 0.8635
Epoch 38/200
249/249 [==============================] - 0s 60us/step - loss: 0.3573 - acc: 0.8353
Epoch 39/200
249/249 [==============================] - 0s 68us/step - loss: 0.3679 - acc: 0.8313
Epoch 40/200
249/249 [==============================] - 0s 60us/step - loss: 0.3503 - acc: 0.8434
Epoch 41/200
249/249 [==============================] - 0s 56us/step - loss: 0.3411 - acc: 0.8554
Epoch 42/200
249/249 [==============================] - 0s 72us/step - loss: 0.3791 - acc: 0.8233
Epoch 43/200
249/249 [==============================] - 0s 72us/step - loss: 0.3878 - acc: 0.8233
Epoch 44/200
249/249 [==============================] - 0s 60us/step - loss: 0.3601 - acc: 0.8434
Epoch 45/200
249/249 [==============================] - 0s 76us/step - loss: 0.3402 - acc: 0.8514
Epoch 46/200
249/249 [==============================] - 0s 84us/step - loss: 0.3681 - acc: 0.8193
Epoch 47/200
249/249 [==============================] - 0s 60us/step - loss: 0.3526 - acc: 0.8313
Epoch 48/200
249/249 [==============================] - 0s 72us/step - loss: 0.3506 - acc: 0.8273
Epoch 49/200
249/249 [==============================] - 0s 60us/step - loss: 0.3451 - acc: 0.8353
Epoch 50/200
249/249 [==============================] - 0s 68us/step - loss: 0.3663 - acc: 0.8273
Epoch 51/200
249/249 [==============================] - 0s 76us/step - loss: 0.3455 - acc: 0.8394
Epoch 52/200
249/249 [==============================] - 0s 56us/step - loss: 0.3537 - acc: 0.8193
Epoch 53/200
249/249 [==============================] - 0s 80us/step - loss: 0.3421 - acc: 0.8554
Epoch 54/200
249/249 [==============================] - 0s 68us/step - loss: 0.3427 - acc: 0.8112
Epoch 55/200
249/249 [==============================] - 0s 80us/step - loss: 0.3339 - acc: 0.8715
Epoch 56/200
249/249 [==============================] - 0s 64us/step - loss: 0.3427 - acc: 0.8353
Epoch 57/200
249/249 [==============================] - 0s 52us/step - loss: 0.3274 - acc: 0.8554
Epoch 58/200
249/249 [==============================] - 0s 80us/step - loss: 0.3347 - acc: 0.8514
Epoch 59/200
249/249 [==============================] - 0s 72us/step - loss: 0.3566 - acc: 0.8474
Epoch 60/200
249/249 [==============================] - 0s 92us/step - loss: 0.3299 - acc: 0.8474
Epoch 61/200
249/249 [==============================] - 0s 64us/step - loss: 0.3358 - acc: 0.8514
Epoch 62/200
249/249 [==============================] - 0s 72us/step - loss: 0.3398 - acc: 0.8313
Epoch 63/200
249/249 [==============================] - 0s 56us/step - loss: 0.3069 - acc: 0.8554
Epoch 64/200
249/249 [==============================] - 0s 60us/step - loss: 0.3678 - acc: 0.8474
Epoch 65/200
249/249 [==============================] - 0s 68us/step - loss: 0.3064 - acc: 0.8394
Epoch 66/200
249/249 [==============================] - 0s 64us/step - loss: 0.3469 - acc: 0.8353
Epoch 67/200
249/249 [==============================] - 0s 76us/step - loss: 0.3442 - acc: 0.8594
Epoch 68/200
249/249 [==============================] - 0s 56us/step - loss: 0.3256 - acc: 0.8313
Epoch 69/200
249/249 [==============================] - 0s 56us/step - loss: 0.3452 - acc: 0.8514
Epoch 70/200
249/249 [==============================] - 0s 60us/step - loss: 0.3332 - acc: 0.8675
Epoch 71/200
249/249 [==============================] - 0s 60us/step - loss: 0.3226 - acc: 0.8635
Epoch 72/200
249/249 [==============================] - 0s 80us/step - loss: 0.3545 - acc: 0.8313
Epoch 73/200
249/249 [==============================] - 0s 56us/step - loss: 0.3390 - acc: 0.8594
Epoch 74/200
249/249 [==============================] - 0s 68us/step - loss: 0.2940 - acc: 0.8715
Epoch 75/200
249/249 [==============================] - 0s 80us/step - loss: 0.3182 - acc: 0.8554
Epoch 76/200
249/249 [==============================] - 0s 60us/step - loss: 0.3143 - acc: 0.8474
Epoch 77/200
249/249 [==============================] - 0s 68us/step - loss: 0.3408 - acc: 0.8514
Epoch 78/200
249/249 [==============================] - 0s 68us/step - loss: 0.3319 - acc: 0.8514
Epoch 79/200
249/249 [==============================] - 0s 68us/step - loss: 0.3532 - acc: 0.8434
Epoch 80/200
249/249 [==============================] - 0s 88us/step - loss: 0.3344 - acc: 0.8353
Epoch 81/200
249/249 [==============================] - 0s 56us/step - loss: 0.3513 - acc: 0.8394
Epoch 82/200

249/249 [==============================] - 0s 80us/step - loss: 0.3494 - acc: 0.8835
Epoch 83/200
249/249 [==============================] - 0s 60us/step - loss: 0.3463 - acc: 0.8755
Epoch 84/200
249/249 [==============================] - 0s 68us/step - loss: 0.3423 - acc: 0.8715
Epoch 85/200
249/249 [==============================] - 0s 64us/step - loss: 0.3225 - acc: 0.8715
Epoch 86/200
249/249 [==============================] - 0s 80us/step - loss: 0.3565 - acc: 0.8394
Epoch 87/200
249/249 [==============================] - 0s 72us/step - loss: 0.3245 - acc: 0.8353
Epoch 88/200
249/249 [==============================] - 0s 72us/step - loss: 0.3185 - acc: 0.8715
Epoch 89/200
249/249 [==============================] - 0s 68us/step - loss: 0.3177 - acc: 0.8353
Epoch 90/200
249/249 [==============================] - 0s 84us/step - loss: 0.2928 - acc: 0.8715
Epoch 91/200
249/249 [==============================] - 0s 72us/step - loss: 0.3339 - acc: 0.8715
Epoch 92/200
249/249 [==============================] - 0s 56us/step - loss: 0.3080 - acc: 0.8675
Epoch 93/200
249/249 [==============================] - 0s 60us/step - loss: 0.3568 - acc: 0.8755
Epoch 94/200
249/249 [==============================] - 0s 92us/step - loss: 0.3242 - acc: 0.8675
Epoch 95/200
249/249 [==============================] - 0s 64us/step - loss: 0.3472 - acc: 0.8474
Epoch 96/200
249/249 [==============================] - 0s 64us/step - loss: 0.3341 - acc: 0.8554
Epoch 97/200
249/249 [==============================] - 0s 72us/step - loss: 0.2755 - acc: 0.8675
Epoch 98/200
249/249 [==============================] - 0s 60us/step - loss: 0.3024 - acc: 0.8474
Epoch 99/200
249/249 [==============================] - 0s 60us/step - loss: 0.3054 - acc: 0.8554
Epoch 100/200
249/249 [==============================] - 0s 76us/step - loss: 0.3088 - acc: 0.8635
Epoch 101/200
249/249 [==============================] - 0s 60us/step - loss: 0.3442 - acc: 0.8594
Epoch 102/200
249/249 [==============================] - 0s 56us/step - loss: 0.3096 - acc: 0.8474
Epoch 103/200
249/249 [==============================] - 0s 52us/step - loss: 0.3434 - acc: 0.8434
Epoch 104/200
249/249 [==============================] - 0s 68us/step - loss: 0.3120 - acc: 0.8635
Epoch 105/200
249/249 [==============================] - 0s 76us/step - loss: 0.3010 - acc: 0.8715
Epoch 106/200
249/249 [==============================] - 0s 60us/step - loss: 0.3695 - acc: 0.8795
Epoch 107/200
249/249 [==============================] - 0s 64us/step - loss: 0.3498 - acc: 0.8434
Epoch 108/200
249/249 [==============================] - 0s 60us/step - loss: 0.3205 - acc: 0.8755
Epoch 109/200
249/249 [==============================] - 0s 60us/step - loss: 0.3124 - acc: 0.8594
Epoch 110/200
249/249 [==============================] - 0s 64us/step - loss: 0.3350 - acc: 0.8594
Epoch 111/200
249/249 [==============================] - 0s 64us/step - loss: 0.3752 - acc: 0.8514
Epoch 112/200
249/249 [==============================] - 0s 64us/step - loss: 0.3349 - acc: 0.8594
Epoch 113/200
249/249 [==============================] - 0s 72us/step - loss: 0.3221 - acc: 0.8835
Epoch 114/200
249/249 [==============================] - 0s 68us/step - loss: 0.3529 - acc: 0.8554
Epoch 115/200
249/249 [==============================] - 0s 72us/step - loss: 0.3173 - acc: 0.8715
Epoch 116/200
249/249 [==============================] - 0s 68us/step - loss: 0.3552 - acc: 0.8755
Epoch 117/200
249/249 [==============================] - 0s 80us/step - loss: 0.3078 - acc: 0.8755
Epoch 118/200
249/249 [==============================] - 0s 72us/step - loss: 0.3341 - acc: 0.8675
Epoch 119/200
249/249 [==============================] - 0s 64us/step - loss: 0.3028 - acc: 0.8755
Epoch 120/200
249/249 [==============================] - 0s 68us/step - loss: 0.3242 - acc: 0.8755
Epoch 121/200
249/249 [==============================] - 0s 72us/step - loss: 0.2788 - acc: 0.8916
Epoch 122/200
249/249 [==============================] - 0s 68us/step - loss: 0.3067 - acc: 0.8916
Epoch 123/200
249/249 [==============================] - 0s 60us/step - loss: 0.3079 - acc: 0.8755
Epoch 124/200
249/249 [==============================] - 0s 68us/step - loss: 0.3531 - acc: 0.8554
Epoch 125/200
249/249 [==============================] - 0s 76us/step - loss: 0.3391 - acc: 0.8755
Epoch 126/200
249/249 [==============================] - 0s 60us/step - loss: 0.3486 - acc: 0.8635
Epoch 127/200
249/249 [==============================] - 0s 76us/step - loss: 0.3428 - acc: 0.8554
Epoch 128/200
249/249 [==============================] - 0s 76us/step - loss: 0.3108 - acc: 0.8996
Epoch 129/200
249/249 [==============================] - 0s 72us/step - loss: 0.3493 - acc: 0.8795
Epoch 130/200
249/249 [==============================] - 0s 76us/step - loss: 0.3209 - acc: 0.8835
Epoch 131/200
249/249 [==============================] - ETA: 0s - loss: 0.1795 - acc: 0.900 - 0s 80us/step - loss: 0.3134 - acc: 0.8594
Epoch 132/200
249/249 [==============================] - 0s 68us/step - loss: 0.3231 - acc: 0.8514
Epoch 133/200
249/249 [==============================] - 0s 72us/step - loss: 0.3415 - acc: 0.8394
Epoch 134/200
249/249 [==============================] - 0s 72us/step - loss: 0.3321 - acc: 0.8996
Epoch 135/200
249/249 [==============================] - 0s 76us/step - loss: 0.3236 - acc: 0.8835
Epoch 136/200
249/249 [==============================] - 0s 64us/step - loss: 0.3318 - acc: 0.8755
Epoch 137/200
249/249 [==============================] - 0s 60us/step - loss: 0.3136 - acc: 0.8795
Epoch 138/200
249/249 [==============================] - 0s 80us/step - loss: 0.3472 - acc: 0.8715
Epoch 139/200
249/249 [==============================] - 0s 72us/step - loss: 0.3316 - acc: 0.8474
Epoch 140/200
249/249 [==============================] - 0s 72us/step - loss: 0.2963 - acc: 0.8876
Epoch 141/200
249/249 [==============================] - 0s 76us/step - loss: 0.2936 - acc: 0.8554
Epoch 142/200
249/249 [==============================] - 0s 68us/step - loss: 0.3505 - acc: 0.8474
Epoch 143/200
249/249 [==============================] - 0s 68us/step - loss: 0.3005 - acc: 0.8795
Epoch 144/200
249/249 [==============================] - 0s 64us/step - loss: 0.3172 - acc: 0.8635
Epoch 145/200
249/249 [==============================] - 0s 68us/step - loss: 0.3061 - acc: 0.8795
Epoch 146/200
249/249 [==============================] - 0s 64us/step - loss: 0.3358 - acc: 0.8635
Epoch 147/200
249/249 [==============================] - 0s 72us/step - loss: 0.3042 - acc: 0.8554
Epoch 148/200
249/249 [==============================] - 0s 64us/step - loss: 0.3490 - acc: 0.8675
Epoch 149/200
249/249 [==============================] - 0s 68us/step - loss: 0.3398 - acc: 0.8755
Epoch 150/200
249/249 [==============================] - 0s 68us/step - loss: 0.3438 - acc: 0.8675
Epoch 151/200
249/249 [==============================] - 0s 52us/step - loss: 0.3017 - acc: 0.8916
Epoch 152/200
249/249 [==============================] - 0s 52us/step - loss: 0.3209 - acc: 0.8755
Epoch 153/200
249/249 [==============================] - 0s 56us/step - loss: 0.3201 - acc: 0.8635
Epoch 154/200
249/249 [==============================] - 0s 64us/step - loss: 0.3409 - acc: 0.8675
Epoch 155/200
249/249 [==============================] - 0s 64us/step - loss: 0.2951 - acc: 0.8715
Epoch 156/200
249/249 [==============================] - 0s 144us/step - loss: 0.2947 - acc: 0.8876
Epoch 157/200
249/249 [==============================] - 0s 84us/step - loss: 0.3364 - acc: 0.8554
Epoch 158/200
249/249 [==============================] - 0s 68us/step - loss: 0.3103 - acc: 0.8715
Epoch 159/200
249/249 [==============================] - 0s 64us/step - loss: 0.3230 - acc: 0.8554
Epoch 160/200
249/249 [==============================] - 0s 68us/step - loss: 0.3067 - acc: 0.8594
Epoch 161/200
249/249 [==============================] - 0s 88us/step - loss: 0.3085 - acc: 0.8594
Epoch 162/200
249/249 [==============================] - 0s 52us/step - loss: 0.3186 - acc: 0.8394
Epoch 163/200
249/249 [==============================] - 0s 48us/step - loss: 0.3115 - acc: 0.8795
Epoch 164/200

249/249 [==============================] - 0s 52us/step - loss: 0.2806 - acc: 0.8996
Epoch 165/200
249/249 [==============================] - 0s 21us/step - loss: 0.3554 - acc: 0.8594
Epoch 166/200
249/249 [==============================] - 0s 63us/step - loss: 0.3120 - acc: 0.8835
Epoch 167/200
249/249 [==============================] - 0s 72us/step - loss: 0.3245 - acc: 0.8594
Epoch 168/200
249/249 [==============================] - 0s 44us/step - loss: 0.3131 - acc: 0.8835
Epoch 169/200
249/249 [==============================] - 0s 48us/step - loss: 0.3053 - acc: 0.8715
Epoch 170/200
249/249 [==============================] - 0s 29us/step - loss: 0.3297 - acc: 0.8675
Epoch 171/200
249/249 [==============================] - 0s 63us/step - loss: 0.3407 - acc: 0.8554
Epoch 172/200
249/249 [==============================] - 0s 0us/step - loss: 0.3307 - acc: 0.8474
Epoch 173/200
249/249 [==============================] - 0s 63us/step - loss: 0.2807 - acc: 0.8594
Epoch 174/200
249/249 [==============================] - 0s 63us/step - loss: 0.3167 - acc: 0.8755
Epoch 175/200
249/249 [==============================] - 0s 63us/step - loss: 0.2918 - acc: 0.8755
Epoch 176/200
249/249 [==============================] - 0s 30us/step - loss: 0.3216 - acc: 0.8795
Epoch 177/200
249/249 [==============================] - 0s 84us/step - loss: 0.3339 - acc: 0.8795
Epoch 178/200
249/249 [==============================] - 0s 44us/step - loss: 0.2780 - acc: 0.8594
Epoch 179/200
249/249 [==============================] - 0s 49us/step - loss: 0.2897 - acc: 0.8795
Epoch 180/200
249/249 [==============================] - 0s 0us/step - loss: 0.2801 - acc: 0.8916
Epoch 181/200
249/249 [==============================] - 0s 63us/step - loss: 0.3460 - acc: 0.8594
Epoch 182/200
249/249 [==============================] - 0s 63us/step - loss: 0.3385 - acc: 0.8635
Epoch 183/200
249/249 [==============================] - 0s 63us/step - loss: 0.3005 - acc: 0.8916
Epoch 184/200
249/249 [==============================] - 0s 28us/step - loss: 0.3136 - acc: 0.8635
Epoch 185/200
249/249 [==============================] - 0s 63us/step - loss: 0.3143 - acc: 0.8795
Epoch 186/200
249/249 [==============================] - 0s 63us/step - loss: 0.3542 - acc: 0.8474
Epoch 187/200
249/249 [==============================] - 0s 0us/step - loss: 0.3294 - acc: 0.8394
Epoch 188/200
249/249 [==============================] - 0s 63us/step - loss: 0.3252 - acc: 0.8675
Epoch 189/200
249/249 [==============================] - 0s 63us/step - loss: 0.3132 - acc: 0.8594
Epoch 190/200
249/249 [==============================] - 0s 63us/step - loss: 0.2905 - acc: 0.8916
Epoch 191/200
249/249 [==============================] - 0s 63us/step - loss: 0.2964 - acc: 0.9036
Epoch 192/200
249/249 [==============================] - 0s 26us/step - loss: 0.3408 - acc: 0.8353
Epoch 193/200
249/249 [==============================] - 0s 63us/step - loss: 0.3434 - acc: 0.8554
Epoch 194/200
249/249 [==============================] - 0s 77us/step - loss: 0.2783 - acc: 0.8956
Epoch 195/200
249/249 [==============================] - 0s 56us/step - loss: 0.2908 - acc: 0.8835
Epoch 196/200
249/249 [==============================] - 0s 52us/step - loss: 0.2836 - acc: 0.8835
Epoch 197/200
249/249 [==============================] - 0s 52us/step - loss: 0.3131 - acc: 0.8956
Epoch 198/200
249/249 [==============================] - 0s 56us/step - loss: 0.2946 - acc: 0.8835
Epoch 199/200
249/249 [==============================] - 0s 56us/step - loss: 0.3364 - acc: 0.8755
Epoch 200/200
249/249 [==============================] - 0s 60us/step - loss: 0.3159 - acc: 0.8675

In [21]:
#y_pred_class is the predcition & y_pred_prob is probabilities of the prediction

y_pred_class=model.predict(x_test)
y_pred_prob=model.predict_proba(x_test)

In [22]:
##Explore the y_pred_class
y_pred_class[:5]

array([[0.10599926],
       [0.0005706 ],
       [0.04020166],
       [0.02961734],
       [0.00616115]], dtype=float32)

In [23]:
##Set threshold all values above threshold are 1 and #below 0
y_pred_class=y_pred_class>0.5

In [24]:
# # false means 0 and true mean 1
print(y_pred_class[:5])

[[False]
 [False]
 [False]
 [False]
 [False]]

In [25]:
y_pred_class.astype(int)[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [26]:
#Calculate accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_class)

0.8611111111111112

 ## Compute the Null Accuracy

In [27]:
# Use the value_count function to calculate distinct class values
ytest.value_counts()

0    91
1    17
Name: Readmitted, dtype: int64

In [28]:
##use head function and divide it by lenght of ytest
ytest.value_counts().head(1)/len(ytest)

0    0.842593
Name: Readmitted, dtype: float64