In [1]:
import numpy as np
import pandas as pd

In [2]:
!ls Applied-Deep-Learning-with-Keras

Lesson01  Lesson03  Lesson05  Lesson07	Lesson09  README.md
Lesson02  Lesson04  Lesson06  Lesson08	LICENSE

In [3]:
!ls Applied-Deep-Learning-with-Keras/Lesson06/data

Flu.csv  Health_Data.csv

In [4]:
!head Applied-Deep-Learning-with-Keras/Lesson06/data/Health_Data.csv

Patient_id,Age,Admission_type,PreExistingDisease,PreviousSurgery,Gender,Smoker,Homeless,DaysinHospital,Readmitted
1,33,Urgent,Y,0,M,1,0,1,0
2,34,Emergency,N,0,M,1,0,22,0
3,88,Trauma,Y,1,M,1,1,100,1
4,56,Elective,Y,0,M,1,0,2,0
5,45,Trauma,Y,0,M,1,0,34,0
6,23,Elective,N,0,M,0,0,123,0
7,67,Elective,N,0,M,0,0,23,0
8,55,Elective,N,0,M,1,0,123,1
9,77,Trauma,N,0,F,1,0,44,0

In [5]:
patient_data = pd.read_csv("Applied-Deep-Learning-with-Keras/Lesson06/data/Health_Data.csv")

In [6]:
patient_data.head(20)

,Patient_id,Age,Admission_type,PreExistingDisease,PreviousSurgery,Gender,Smoker,Homeless,DaysinHospital,Readmitted
0,1,33,Urgent,Y,0,M,1,0,1,0
1,2,34,Emergency,N,0,M,1,0,22,0
2,3,88,Trauma,Y,1,M,1,1,100,1
3,4,56,Elective,Y,0,M,1,0,2,0
4,5,45,Trauma,Y,0,M,1,0,34,0
5,6,23,Elective,N,0,M,0,0,123,0
6,7,67,Elective,N,0,M,0,0,23,0
7,8,55,Elective,N,0,M,1,0,123,1
8,9,77,Trauma,N,0,F,1,0,44,0
9,10,88,Emergency,N,0,M,1,0,3,1
10,11,76,Urgent,N,0,F,1,0,2,1
11,12,64,Urgent,N,0,F,1,1,45,0
12,13,53,Urgent,N,0,F,0,1,32,0
13,14,0,Newborn,N,0,M,0,0,33,0
14,15,0,Newborn,N,0,F,0,0,22,0
15,16,0,Newborn,N,0,M,0,0,7,0
16,17,0,Newborn,N,0,F,0,0,7,0
17,18,54,Urgent,Y,1,M,1,0,32,0
18,19,5,Emergency,Y,1,M,1,0,43,0
19,20,4,Emergency,Y,0,F,1,0,32,0

In [7]:
patient_data.describe()

,Patient_id,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,Readmitted
count,357.00000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000
mean,179.00000,42.574230,0.341737,0.596639,0.378151,43.182073,0.193277
std,103.20126,29.274624,0.474957,0.491261,0.485606,47.362609,0.395423
min,1.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,90.00000,14.000000,0.000000,0.000000,0.000000,12.000000,0.000000
50%,179.00000,35.000000,0.000000,1.000000,0.000000,32.000000,0.000000
75%,268.00000,67.000000,1.000000,1.000000,1.000000,55.000000,0.000000
max,357.00000,96.000000,1.000000,1.000000,1.000000,352.000000,1.000000

In [8]:
patient_data.describe(include=['object'])

       Admission_type PreExistingDisease Gender
count             357                357    357
unique              5                  2      2
top            Urgent                  N      F
freq              131                228    186

In [9]:
patient_data.head()

,Patient_id,Age,Admission_type,PreExistingDisease,PreviousSurgery,Gender,Smoker,Homeless,DaysinHospital,Readmitted
0,1,33,Urgent,Y,0,M,1,0,1,0
1,2,34,Emergency,N,0,M,1,0,22,0
2,3,88,Trauma,Y,1,M,1,1,100,1
3,4,56,Elective,Y,0,M,1,0,2,0
4,5,45,Trauma,Y,0,M,1,0,34,0

In [10]:
help(pd.get_dummies)

Help on function get_dummies in module pandas.core.reshape.reshape:

get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None) -> 'DataFrame'
    Convert categorical variable into dummy/indicator variables.

    Parameters
    ----------
    data : array-like, Series, or DataFrame
        Data of which to get dummy indicators.
    prefix : str, list of str, or dict of str, default None
        String to append DataFrame column names.
        Pass a list with length equal to the number of columns
        when calling get_dummies on a DataFrame. Alternatively, `prefix`
        can be a dictionary mapping column names to prefixes.
    prefix_sep : str, default '_'
        If appending prefix, separator/delimiter to use. Or pass a
        list or dictionary as with `prefix`.
    dummy_na : bool, default False
        Add a column to indicate NaNs, if False NaNs are ignored.
    columns : list-like, default None
        Column names in the DataFrame to be encoded.
        If `columns` is None then all the columns with
        `object` or `category` dtype will be converted.
    sparse : bool, default False
        Whether the dummy-encoded columns should be backed by
        a :class:`SparseArray` (True) or a regular NumPy array (False).
    drop_first : bool, default False
        Whether to get k-1 dummies out of k categorical levels by removing the
        first level.
    dtype : dtype, default np.uint8
        Data type for new columns. Only a single dtype is allowed.

        .. versionadded:: 0.23.0

    Returns
    -------
    DataFrame
        Dummy-coded data.

    See Also
    --------
    Series.str.get_dummies : Convert Series to dummy codes.

    Examples
    --------
    >>> s = pd.Series(list('abca'))

    >>> pd.get_dummies(s)
       a  b  c
    0  1  0  0
    1  0  1  0
    2  0  0  1
    3  1  0  0

    >>> s1 = ['a', 'b', np.nan]

    >>> pd.get_dummies(s1)
       a  b
    0  1  0
    1  0  1
    2  0  0

    >>> pd.get_dummies(s1, dummy_na=True)
       a  b  NaN
    0  1  0    0
    1  0  1    0
    2  0  0    1

    >>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
    ...                    'C': [1, 2, 3]})

    >>> pd.get_dummies(df, prefix=['col1', 'col2'])
       C  col1_a  col1_b  col2_a  col2_b  col2_c
    0  1       1       0       0       1       0
    1  2       0       1       1       0       0
    2  3       1       0       0       0       1

    >>> pd.get_dummies(pd.Series(list('abcaa')))
       a  b  c
    0  1  0  0
    1  0  1  0
    2  0  0  1
    3  1  0  0
    4  1  0  0

    >>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
       b  c
    0  0  0
    1  1  0
    2  0  1
    3  0  0
    4  0  0

    >>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
         a    b    c
    0  1.0  0.0  0.0
    1  0.0  1.0  0.0
    2  0.0  0.0  1.0

In [11]:
X = patient_data.iloc
print(X)

<pandas.core.indexing._iLocIndexer object at 0x7f66926ebad0>

In [12]:
X = patient_data.iloc[:,1:9]
print(X)

     Age Admission_type PreExistingDisease  PreviousSurgery Gender  Smoker  \
0     33         Urgent                  Y                0      M       1
1     34      Emergency                  N                0      M       1
2     88         Trauma                  Y                1      M       1
3     56       Elective                  Y                0      M       1
4     45         Trauma                  Y                0      M       1
..   ...            ...                ...              ...    ...     ...
352   14         Trauma                  Y                1      M       1
353   45         Trauma                  N                0      F       1
354   67         Trauma                  N                1      M       1
355   43         Trauma                  Y                1      M       0
356    2         Trauma                  Y                1      F       0

     Homeless  DaysinHospital
0           0               1
1           0              22
2           1             100
3           0               2
4           0              34
..        ...             ...
352         1               2
353         1               2
354         1               2
355         1               2
356         1               2

[357 rows x 8 columns]

In [13]:
y = patient_data.iloc[:,9]
print(y)

0      0
1      0
2      1
3      0
4      0
      ..
352    0
353    0
354    0
355    0
356    0
Name: Readmitted, Length: 357, dtype: int64

In [14]:
print(X.iloc[:,1])

0         Urgent
1      Emergency
2         Trauma
3       Elective
4         Trauma
         ...
352       Trauma
353       Trauma
354       Trauma
355       Trauma
356       Trauma
Name: Admission_type, Length: 357, dtype: object

In [15]:
SpecType = pd.get_dummies(X.iloc[:,1], drop_first = True, prefix = 'SpecType')

In [16]:
print(SpecType)

     SpecType_Emergency  SpecType_Newborn  SpecType_Trauma  SpecType_Urgent
0                     0                 0                0                1
1                     1                 0                0                0
2                     0                 0                1                0
3                     0                 0                0                0
4                     0                 0                1                0
..                  ...               ...              ...              ...
352                   0                 0                1                0
353                   0                 0                1                0
354                   0                 0                1                0
355                   0                 0                1                0
356                   0                 0                1                0

[357 rows x 4 columns]

In [17]:
PreDie = pd.get_dummies(X.iloc[:,2], drop_first = True, prefix = 'PreDie')

In [18]:
print(PreDie)

     PreDie_Y
0           1
1           0
2           1
3           1
4           1
..        ...
352         1
353         0
354         0
355         1
356         1

[357 rows x 1 columns]

In [19]:
X.drop(['Admission_type', 'PreExistingDisease', 'Gender'], axis = 1, inplace = True)

In [20]:
X = pd.concat([X, SpecType, PreDie],axis = 1)

In [21]:
X.head()

,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,SpecType_Emergency,SpecType_Newborn,SpecType_Trauma,SpecType_Urgent,PreDie_Y
0,33,0,1,0,1,0,0,0,1,1
1,34,0,1,0,22,1,0,0,0,0
2,88,1,1,1,100,0,0,1,0,1
3,56,0,1,0,2,0,0,0,0,1
4,45,0,1,0,34,0,0,1,0,1

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 1
)

In [24]:
print(X_train.shape)
print(y_train.shape)

(249, 10)
(249,)

In [25]:
print(X_test.shape)
print(y_test.shape)

(108, 10)
(108,)

In [26]:
print(108/357)
print(248/357)

0.3025210084033613
0.6946778711484594

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
print(X_train)

     Age  PreviousSurgery  Smoker  Homeless  DaysinHospital  \
62    23                1       1         0              56
154    6                0       1         1              77
185   44                0       0         0              74
102   88                0       1         1               3
207   91                0       1         1              99
..   ...              ...     ...       ...             ...
203   91                1       1         0              96
255   35                1       1         1              25
72    48                0       0         0              14
235   91                0       1         1             123
37    77                0       1         0              44

     SpecType_Emergency  SpecType_Newborn  SpecType_Trauma  SpecType_Urgent  \
62                    0                 0                1                0
154                   0                 0                0                1
185                   1                 0                0                0
102                   0                 0                1                0
207                   0                 0                1                0
..                  ...               ...              ...              ...
203                   0                 0                1                0
255                   0                 0                0                1
72                    0                 0                0                0
235                   0                 0                0                1
37                    0                 0                0                1

     PreDie_Y
62          0
154         0
185         0
102         0
207         1
..        ...
203         1
255         0
72          0
235         1
37          0

[249 rows x 10 columns]

In [29]:
sc = StandardScaler()

X_train = sc.fit_transform(X_train)

print(X_train)

[[-0.63137586  1.30633906  0.85391256 ...  1.94639707 -0.78541907
  -0.75891328]
 [-1.20477514 -0.76549805  0.85391256 ... -0.51376978  1.27320565
  -0.75891328]
 [ 0.07694089 -0.76549805 -1.17108009 ... -0.51376978 -0.78541907
  -0.75891328]
 ...
 [ 0.21185837 -0.76549805 -1.17108009 ... -0.51376978 -0.78541907
  -0.75891328]
 [ 1.66222125 -0.76549805  0.85391256 ... -0.51376978  1.27320565
   1.31767361]
 [ 1.19001008 -0.76549805  0.85391256 ... -0.51376978  1.27320565
  -0.75891328]]

In [30]:
X_train = pd.DataFrame(X_train, columns= X_test.columns)
print(X_train)

          Age  PreviousSurgery    Smoker  Homeless  DaysinHospital  \
0   -0.631376         1.306339  0.853913 -0.745822        0.288742
1   -1.204775        -0.765498  0.853913  1.340803        0.739842
2    0.076941        -0.765498 -1.171080 -0.745822        0.675399
3    1.561033        -0.765498  0.853913  1.340803       -0.849748
4    1.662221        -0.765498  0.853913  1.340803        1.212423
..        ...              ...       ...       ...             ...
244  1.662221         1.306339  0.853913 -0.745822        1.147980
245 -0.226623         1.306339  0.853913  1.340803       -0.377168
246  0.211858        -0.765498 -1.171080 -0.745822       -0.613458
247  1.662221        -0.765498  0.853913  1.340803        1.727966
248  1.190010        -0.765498  0.853913 -0.745822        0.030971

     SpecType_Emergency  SpecType_Newborn  SpecType_Trauma  SpecType_Urgent  \
0             -0.341456         -0.295527         1.946397        -0.785419
1             -0.341456         -0.295527        -0.513770         1.273206
2              2.928638         -0.295527        -0.513770        -0.785419
3             -0.341456         -0.295527         1.946397        -0.785419
4             -0.341456         -0.295527         1.946397        -0.785419
..                  ...               ...              ...              ...
244           -0.341456         -0.295527         1.946397        -0.785419
245           -0.341456         -0.295527        -0.513770         1.273206
246           -0.341456         -0.295527        -0.513770        -0.785419
247           -0.341456         -0.295527        -0.513770         1.273206
248           -0.341456         -0.295527        -0.513770         1.273206

     PreDie_Y
0   -0.758913
1   -0.758913
2   -0.758913
3   -0.758913
4    1.317674
..        ...
244  1.317674
245 -0.758913
246 -0.758913
247  1.317674
248 -0.758913

[249 rows x 10 columns]

In [31]:
X_train.head()

,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,SpecType_Emergency,SpecType_Newborn,SpecType_Trauma,SpecType_Urgent,PreDie_Y
0,-0.631376,1.306339,0.853913,-0.745822,0.288742,-0.341456,-0.295527,1.946397,-0.785419,-0.758913
1,-1.204775,-0.765498,0.853913,1.340803,0.739842,-0.341456,-0.295527,-0.513770,1.273206,-0.758913
2,0.076941,-0.765498,-1.171080,-0.745822,0.675399,2.928638,-0.295527,-0.513770,-0.785419,-0.758913
3,1.561033,-0.765498,0.853913,1.340803,-0.849748,-0.341456,-0.295527,1.946397,-0.785419,-0.758913
4,1.662221,-0.765498,0.853913,1.340803,1.212423,-0.341456,-0.295527,1.946397,-0.785419,1.317674

In [32]:
X_test

,Age,PreviousSurgery,Smoker,Homeless,DaysinHospital,SpecType_Emergency,SpecType_Newborn,SpecType_Trauma,SpecType_Urgent,PreDie_Y
273,77,0,1,0,44,0,0,1,0,0
234,92,0,1,1,142,0,0,0,1,1
333,39,1,1,1,35,0,0,0,0,1
165,44,0,1,0,53,1,0,0,0,0
321,34,0,1,0,352,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
199,76,0,1,0,46,0,0,0,1,0
0,33,0,1,0,1,0,0,0,1,1
167,23,0,0,1,43,1,0,0,0,0
105,53,0,0,1,32,0,0,1,0,0
147,88,0,1,0,3,0,0,0,1,0

In [33]:
X_test = sc.transform(X_test)
X_test = pd.DataFrame(X_test, columns= X_train.columns)

In [34]:
X_train_np = X_train.values
X_test_np = X_test.values
y_train_np = y_train.values
y_test_np = y_test.values

In [35]:
print(type(X_train_np))

<class 'numpy.ndarray'>

In [36]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

In [37]:
model = Sequential()

In [38]:
model.add(Dense(units = 6, activation = 'relu', kernel_initializer = 'uniform', input_dim = 10))
model.add(Dropout(rate = 0.3))

In [39]:
model.add(Dense(units = 6, activation = 'tanh', kernel_initializer = 'uniform'))
model.add(Dropout(rate = 0.3))

In [40]:
model.add(Dense(units = 1, activation = 'sigmoid', kernel_initializer = 'uniform'))

In [41]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [42]:
model.fit(X_train, y_train, epochs = 200, batch_size = 20)

Epoch 1/200
13/13 [==============================] - 0s 666us/step - loss: 0.6909 - accuracy: 0.8072
Epoch 2/200
13/13 [==============================] - 0s 572us/step - loss: 0.6852 - accuracy: 0.8072
Epoch 3/200
13/13 [==============================] - 0s 728us/step - loss: 0.6786 - accuracy: 0.8072
Epoch 4/200
13/13 [==============================] - 0s 661us/step - loss: 0.6689 - accuracy: 0.8072
Epoch 5/200
13/13 [==============================] - 0s 628us/step - loss: 0.6581 - accuracy: 0.8072
Epoch 6/200
13/13 [==============================] - 0s 655us/step - loss: 0.6415 - accuracy: 0.8072
Epoch 7/200
13/13 [==============================] - 0s 966us/step - loss: 0.6206 - accuracy: 0.8072
Epoch 8/200
13/13 [==============================] - 0s 528us/step - loss: 0.5972 - accuracy: 0.8072
Epoch 9/200
13/13 [==============================] - 0s 689us/step - loss: 0.5744 - accuracy: 0.8072
Epoch 10/200
13/13 [==============================] - 0s 500us/step - loss: 0.5477 - accuracy: 0.8072
Epoch 11/200
13/13 [==============================] - 0s 634us/step - loss: 0.5245 - accuracy: 0.8072
Epoch 12/200
13/13 [==============================] - 0s 513us/step - loss: 0.4975 - accuracy: 0.8072
Epoch 13/200
13/13 [==============================] - 0s 618us/step - loss: 0.4751 - accuracy: 0.8072
Epoch 14/200
13/13 [==============================] - 0s 601us/step - loss: 0.4629 - accuracy: 0.8072
Epoch 15/200
13/13 [==============================] - 0s 538us/step - loss: 0.4576 - accuracy: 0.8072
Epoch 16/200
13/13 [==============================] - 0s 541us/step - loss: 0.4447 - accuracy: 0.8072
Epoch 17/200
13/13 [==============================] - 0s 514us/step - loss: 0.4309 - accuracy: 0.8072
Epoch 18/200
13/13 [==============================] - 0s 556us/step - loss: 0.4352 - accuracy: 0.8072
Epoch 19/200
13/13 [==============================] - 0s 752us/step - loss: 0.4165 - accuracy: 0.8072
Epoch 20/200
13/13 [==============================] - 0s 538us/step - loss: 0.4130 - accuracy: 0.8072
Epoch 21/200
13/13 [==============================] - 0s 555us/step - loss: 0.4156 - accuracy: 0.8072
Epoch 22/200
13/13 [==============================] - 0s 561us/step - loss: 0.3948 - accuracy: 0.8072
Epoch 23/200
13/13 [==============================] - 0s 571us/step - loss: 0.4037 - accuracy: 0.8072
Epoch 24/200
13/13 [==============================] - 0s 657us/step - loss: 0.3984 - accuracy: 0.8072
Epoch 25/200
13/13 [==============================] - 0s 634us/step - loss: 0.3846 - accuracy: 0.8072
Epoch 26/200
13/13 [==============================] - 0s 611us/step - loss: 0.3823 - accuracy: 0.8072
Epoch 27/200
13/13 [==============================] - 0s 653us/step - loss: 0.3794 - accuracy: 0.8072
Epoch 28/200
13/13 [==============================] - 0s 718us/step - loss: 0.3722 - accuracy: 0.8072
Epoch 29/200
13/13 [==============================] - 0s 594us/step - loss: 0.3724 - accuracy: 0.8072
Epoch 30/200
13/13 [==============================] - 0s 633us/step - loss: 0.3767 - accuracy: 0.8072
Epoch 31/200
13/13 [==============================] - 0s 501us/step - loss: 0.3725 - accuracy: 0.8072
Epoch 32/200
13/13 [==============================] - 0s 602us/step - loss: 0.3681 - accuracy: 0.8072
Epoch 33/200
13/13 [==============================] - 0s 626us/step - loss: 0.3700 - accuracy: 0.8072
Epoch 34/200
13/13 [==============================] - 0s 612us/step - loss: 0.3617 - accuracy: 0.8072
Epoch 35/200
13/13 [==============================] - 0s 671us/step - loss: 0.3630 - accuracy: 0.8072
Epoch 36/200
13/13 [==============================] - 0s 614us/step - loss: 0.3578 - accuracy: 0.8072
Epoch 37/200
13/13 [==============================] - 0s 692us/step - loss: 0.3488 - accuracy: 0.8072
Epoch 38/200
13/13 [==============================] - 0s 640us/step - loss: 0.3582 - accuracy: 0.8072
Epoch 39/200
13/13 [==============================] - 0s 628us/step - loss: 0.3363 - accuracy: 0.8072
Epoch 40/200
13/13 [==============================] - 0s 694us/step - loss: 0.3408 - accuracy: 0.8072
Epoch 41/200
13/13 [==============================] - 0s 635us/step - loss: 0.3250 - accuracy: 0.8072
Epoch 42/200
13/13 [==============================] - 0s 743us/step - loss: 0.3495 - accuracy: 0.8072
Epoch 43/200
13/13 [==============================] - 0s 607us/step - loss: 0.3336 - accuracy: 0.8072
Epoch 44/200
13/13 [==============================] - 0s 868us/step - loss: 0.3388 - accuracy: 0.8072
Epoch 45/200
13/13 [==============================] - 0s 573us/step - loss: 0.3370 - accuracy: 0.8072
Epoch 46/200
13/13 [==============================] - 0s 622us/step - loss: 0.3304 - accuracy: 0.8072
Epoch 47/200
13/13 [==============================] - 0s 556us/step - loss: 0.3163 - accuracy: 0.8072
Epoch 48/200
13/13 [==============================] - 0s 625us/step - loss: 0.3351 - accuracy: 0.8233
Epoch 49/200
13/13 [==============================] - 0s 594us/step - loss: 0.3277 - accuracy: 0.8394
Epoch 50/200
13/13 [==============================] - 0s 546us/step - loss: 0.3032 - accuracy: 0.8635
Epoch 51/200
13/13 [==============================] - 0s 646us/step - loss: 0.3336 - accuracy: 0.8675
Epoch 52/200
13/13 [==============================] - 0s 704us/step - loss: 0.3153 - accuracy: 0.8956
Epoch 53/200
13/13 [==============================] - 0s 655us/step - loss: 0.3002 - accuracy: 0.9157
Epoch 54/200
13/13 [==============================] - 0s 596us/step - loss: 0.2983 - accuracy: 0.8956
Epoch 55/200
13/13 [==============================] - 0s 570us/step - loss: 0.3077 - accuracy: 0.8996
Epoch 56/200
13/13 [==============================] - 0s 598us/step - loss: 0.2951 - accuracy: 0.8996
Epoch 57/200
13/13 [==============================] - 0s 591us/step - loss: 0.2994 - accuracy: 0.9116
Epoch 58/200
13/13 [==============================] - 0s 625us/step - loss: 0.3111 - accuracy: 0.9197
Epoch 59/200
13/13 [==============================] - 0s 564us/step - loss: 0.2965 - accuracy: 0.9237
Epoch 60/200
13/13 [==============================] - 0s 597us/step - loss: 0.2936 - accuracy: 0.9237
Epoch 61/200
13/13 [==============================] - 0s 633us/step - loss: 0.2762 - accuracy: 0.9116
Epoch 62/200
13/13 [==============================] - 0s 548us/step - loss: 0.3049 - accuracy: 0.9197
Epoch 63/200
13/13 [==============================] - 0s 676us/step - loss: 0.2868 - accuracy: 0.9237
Epoch 64/200
13/13 [==============================] - 0s 569us/step - loss: 0.3023 - accuracy: 0.9116
Epoch 65/200
13/13 [==============================] - 0s 551us/step - loss: 0.2838 - accuracy: 0.9116
Epoch 66/200
13/13 [==============================] - 0s 558us/step - loss: 0.2871 - accuracy: 0.9157
Epoch 67/200
13/13 [==============================] - 0s 587us/step - loss: 0.3059 - accuracy: 0.9076
Epoch 68/200
13/13 [==============================] - 0s 591us/step - loss: 0.2931 - accuracy: 0.9076
Epoch 69/200
13/13 [==============================] - 0s 531us/step - loss: 0.2727 - accuracy: 0.9116
Epoch 70/200
13/13 [==============================] - 0s 617us/step - loss: 0.2788 - accuracy: 0.9076
Epoch 71/200
13/13 [==============================] - 0s 521us/step - loss: 0.2684 - accuracy: 0.9116
Epoch 72/200
13/13 [==============================] - 0s 620us/step - loss: 0.2755 - accuracy: 0.9277
Epoch 73/200
13/13 [==============================] - 0s 522us/step - loss: 0.2862 - accuracy: 0.8956
Epoch 74/200
13/13 [==============================] - 0s 538us/step - loss: 0.2918 - accuracy: 0.9116
Epoch 75/200
13/13 [==============================] - 0s 619us/step - loss: 0.2884 - accuracy: 0.9116
Epoch 76/200
13/13 [==============================] - 0s 563us/step - loss: 0.2780 - accuracy: 0.9036
Epoch 77/200
13/13 [==============================] - 0s 642us/step - loss: 0.2777 - accuracy: 0.9116
Epoch 78/200
13/13 [==============================] - 0s 525us/step - loss: 0.2930 - accuracy: 0.9036
Epoch 79/200
13/13 [==============================] - 0s 656us/step - loss: 0.2597 - accuracy: 0.9116
Epoch 80/200
13/13 [==============================] - 0s 547us/step - loss: 0.2982 - accuracy: 0.9116
Epoch 81/200

13/13 [==============================] - 0s 682us/step - loss: 0.2795 - accuracy: 0.9076
Epoch 82/200
13/13 [==============================] - 0s 612us/step - loss: 0.2585 - accuracy: 0.9116
Epoch 83/200
13/13 [==============================] - 0s 527us/step - loss: 0.2717 - accuracy: 0.9157
Epoch 84/200
13/13 [==============================] - 0s 605us/step - loss: 0.2849 - accuracy: 0.9237
Epoch 85/200
13/13 [==============================] - 0s 558us/step - loss: 0.2941 - accuracy: 0.9076
Epoch 86/200
13/13 [==============================] - 0s 610us/step - loss: 0.2689 - accuracy: 0.9116
Epoch 87/200
13/13 [==============================] - 0s 559us/step - loss: 0.2762 - accuracy: 0.9157
Epoch 88/200
13/13 [==============================] - 0s 612us/step - loss: 0.2746 - accuracy: 0.9036
Epoch 89/200
13/13 [==============================] - 0s 575us/step - loss: 0.2491 - accuracy: 0.9157
Epoch 90/200
13/13 [==============================] - 0s 568us/step - loss: 0.2795 - accuracy: 0.9157
Epoch 91/200
13/13 [==============================] - 0s 628us/step - loss: 0.2694 - accuracy: 0.9157
Epoch 92/200
13/13 [==============================] - 0s 537us/step - loss: 0.2844 - accuracy: 0.9076
Epoch 93/200
13/13 [==============================] - 0s 600us/step - loss: 0.2678 - accuracy: 0.9036
Epoch 94/200
13/13 [==============================] - 0s 517us/step - loss: 0.2612 - accuracy: 0.9157
Epoch 95/200
13/13 [==============================] - 0s 634us/step - loss: 0.2874 - accuracy: 0.9076
Epoch 96/200
13/13 [==============================] - 0s 541us/step - loss: 0.2756 - accuracy: 0.9076
Epoch 97/200
13/13 [==============================] - 0s 600us/step - loss: 0.2870 - accuracy: 0.9157
Epoch 98/200
13/13 [==============================] - 0s 563us/step - loss: 0.2940 - accuracy: 0.9036
Epoch 99/200
13/13 [==============================] - 0s 566us/step - loss: 0.2604 - accuracy: 0.9157
Epoch 100/200
13/13 [==============================] - 0s 593us/step - loss: 0.2727 - accuracy: 0.9116
Epoch 101/200
13/13 [==============================] - 0s 536us/step - loss: 0.2723 - accuracy: 0.9036
Epoch 102/200
13/13 [==============================] - 0s 618us/step - loss: 0.2686 - accuracy: 0.9036
Epoch 103/200
13/13 [==============================] - 0s 548us/step - loss: 0.2772 - accuracy: 0.9036
Epoch 104/200
13/13 [==============================] - 0s 571us/step - loss: 0.2693 - accuracy: 0.9116
Epoch 105/200
13/13 [==============================] - 0s 570us/step - loss: 0.2625 - accuracy: 0.9076
Epoch 106/200
13/13 [==============================] - 0s 535us/step - loss: 0.2685 - accuracy: 0.8996
Epoch 107/200
13/13 [==============================] - 0s 587us/step - loss: 0.2422 - accuracy: 0.9197
Epoch 108/200
13/13 [==============================] - 0s 545us/step - loss: 0.2573 - accuracy: 0.9197
Epoch 109/200
13/13 [==============================] - 0s 652us/step - loss: 0.2594 - accuracy: 0.9076
Epoch 110/200
13/13 [==============================] - 0s 531us/step - loss: 0.2685 - accuracy: 0.9116
Epoch 111/200
13/13 [==============================] - 0s 586us/step - loss: 0.2770 - accuracy: 0.9076
Epoch 112/200
13/13 [==============================] - 0s 516us/step - loss: 0.2848 - accuracy: 0.8996
Epoch 113/200
13/13 [==============================] - 0s 601us/step - loss: 0.2860 - accuracy: 0.9036
Epoch 114/200
13/13 [==============================] - 0s 553us/step - loss: 0.2716 - accuracy: 0.9076
Epoch 115/200
13/13 [==============================] - 0s 559us/step - loss: 0.2596 - accuracy: 0.9157
Epoch 116/200
13/13 [==============================] - 0s 750us/step - loss: 0.2375 - accuracy: 0.9197
Epoch 117/200
13/13 [==============================] - 0s 527us/step - loss: 0.2713 - accuracy: 0.9076
Epoch 118/200
13/13 [==============================] - 0s 582us/step - loss: 0.2658 - accuracy: 0.9116
Epoch 119/200
13/13 [==============================] - 0s 535us/step - loss: 0.2686 - accuracy: 0.8996
Epoch 120/200
13/13 [==============================] - 0s 595us/step - loss: 0.2830 - accuracy: 0.8916
Epoch 121/200
13/13 [==============================] - 0s 552us/step - loss: 0.2451 - accuracy: 0.9157
Epoch 122/200
13/13 [==============================] - 0s 544us/step - loss: 0.2580 - accuracy: 0.9237
Epoch 123/200
13/13 [==============================] - 0s 703us/step - loss: 0.2661 - accuracy: 0.9116
Epoch 124/200
13/13 [==============================] - 0s 504us/step - loss: 0.2560 - accuracy: 0.9076
Epoch 125/200
13/13 [==============================] - 0s 617us/step - loss: 0.2644 - accuracy: 0.9237
Epoch 126/200
13/13 [==============================] - 0s 531us/step - loss: 0.2829 - accuracy: 0.8916
Epoch 127/200
13/13 [==============================] - 0s 566us/step - loss: 0.2699 - accuracy: 0.9157
Epoch 128/200
13/13 [==============================] - 0s 512us/step - loss: 0.2627 - accuracy: 0.9116
Epoch 129/200
13/13 [==============================] - 0s 662us/step - loss: 0.2852 - accuracy: 0.9036
Epoch 130/200
13/13 [==============================] - 0s 510us/step - loss: 0.2689 - accuracy: 0.9237
Epoch 131/200
13/13 [==============================] - 0s 562us/step - loss: 0.2500 - accuracy: 0.9157
Epoch 132/200
13/13 [==============================] - 0s 549us/step - loss: 0.2789 - accuracy: 0.9157
Epoch 133/200
13/13 [==============================] - 0s 531us/step - loss: 0.2633 - accuracy: 0.9116
Epoch 134/200
13/13 [==============================] - 0s 631us/step - loss: 0.2711 - accuracy: 0.9076
Epoch 135/200
13/13 [==============================] - 0s 577us/step - loss: 0.2665 - accuracy: 0.9116
Epoch 136/200
13/13 [==============================] - 0s 681us/step - loss: 0.2591 - accuracy: 0.9116
Epoch 137/200
13/13 [==============================] - 0s 521us/step - loss: 0.2731 - accuracy: 0.8835
Epoch 138/200
13/13 [==============================] - 0s 694us/step - loss: 0.2649 - accuracy: 0.8996
Epoch 139/200
13/13 [==============================] - 0s 599us/step - loss: 0.2714 - accuracy: 0.8916
Epoch 140/200
13/13 [==============================] - 0s 664us/step - loss: 0.2648 - accuracy: 0.9116
Epoch 141/200
13/13 [==============================] - 0s 546us/step - loss: 0.2834 - accuracy: 0.9076
Epoch 142/200
13/13 [==============================] - 0s 512us/step - loss: 0.2489 - accuracy: 0.9197
Epoch 143/200
13/13 [==============================] - 0s 577us/step - loss: 0.2642 - accuracy: 0.8956
Epoch 144/200
13/13 [==============================] - 0s 572us/step - loss: 0.2716 - accuracy: 0.9197
Epoch 145/200
13/13 [==============================] - 0s 612us/step - loss: 0.2751 - accuracy: 0.9116
Epoch 146/200
13/13 [==============================] - 0s 526us/step - loss: 0.2537 - accuracy: 0.9197
Epoch 147/200
13/13 [==============================] - 0s 665us/step - loss: 0.2662 - accuracy: 0.9116
Epoch 148/200
13/13 [==============================] - 0s 565us/step - loss: 0.2969 - accuracy: 0.9277
Epoch 149/200
13/13 [==============================] - 0s 500us/step - loss: 0.2529 - accuracy: 0.9197
Epoch 150/200
13/13 [==============================] - 0s 627us/step - loss: 0.2873 - accuracy: 0.9197
Epoch 151/200
13/13 [==============================] - 0s 517us/step - loss: 0.2388 - accuracy: 0.9237
Epoch 152/200
13/13 [==============================] - 0s 542us/step - loss: 0.2604 - accuracy: 0.9076
Epoch 153/200
13/13 [==============================] - 0s 539us/step - loss: 0.2522 - accuracy: 0.9116
Epoch 154/200
13/13 [==============================] - 0s 585us/step - loss: 0.2662 - accuracy: 0.9157
Epoch 155/200
13/13 [==============================] - 0s 563us/step - loss: 0.2389 - accuracy: 0.9157
Epoch 156/200
13/13 [==============================] - 0s 584us/step - loss: 0.2758 - accuracy: 0.9116
Epoch 157/200
13/13 [==============================] - 0s 523us/step - loss: 0.2567 - accuracy: 0.9036
Epoch 158/200
13/13 [==============================] - 0s 569us/step - loss: 0.2605 - accuracy: 0.9036
Epoch 159/200
13/13 [==============================] - 0s 564us/step - loss: 0.2649 - accuracy: 0.9036
Epoch 160/200

13/13 [==============================] - 0s 536us/step - loss: 0.2433 - accuracy: 0.9197
Epoch 161/200
13/13 [==============================] - 0s 564us/step - loss: 0.2618 - accuracy: 0.9036
Epoch 162/200
13/13 [==============================] - 0s 544us/step - loss: 0.2618 - accuracy: 0.9116
Epoch 163/200
13/13 [==============================] - 0s 629us/step - loss: 0.2550 - accuracy: 0.9197
Epoch 164/200
13/13 [==============================] - 0s 545us/step - loss: 0.2936 - accuracy: 0.9116
Epoch 165/200
13/13 [==============================] - 0s 584us/step - loss: 0.2822 - accuracy: 0.9036
Epoch 166/200
13/13 [==============================] - 0s 587us/step - loss: 0.2452 - accuracy: 0.9237
Epoch 167/200
13/13 [==============================] - 0s 556us/step - loss: 0.2800 - accuracy: 0.9036
Epoch 168/200
13/13 [==============================] - 0s 579us/step - loss: 0.2669 - accuracy: 0.9076
Epoch 169/200
13/13 [==============================] - 0s 572us/step - loss: 0.2543 - accuracy: 0.9076
Epoch 170/200
13/13 [==============================] - 0s 587us/step - loss: 0.2688 - accuracy: 0.9076
Epoch 171/200
13/13 [==============================] - 0s 520us/step - loss: 0.2747 - accuracy: 0.9076
Epoch 172/200
13/13 [==============================] - 0s 565us/step - loss: 0.2683 - accuracy: 0.9237
Epoch 173/200
13/13 [==============================] - 0s 516us/step - loss: 0.2272 - accuracy: 0.9197
Epoch 174/200
13/13 [==============================] - 0s 613us/step - loss: 0.2326 - accuracy: 0.9197
Epoch 175/200
13/13 [==============================] - 0s 539us/step - loss: 0.2429 - accuracy: 0.9116
Epoch 176/200
13/13 [==============================] - 0s 587us/step - loss: 0.2691 - accuracy: 0.9036
Epoch 177/200
13/13 [==============================] - 0s 557us/step - loss: 0.2516 - accuracy: 0.9036
Epoch 178/200
13/13 [==============================] - 0s 577us/step - loss: 0.2592 - accuracy: 0.9036
Epoch 179/200
13/13 [==============================] - 0s 537us/step - loss: 0.2623 - accuracy: 0.9116
Epoch 180/200
13/13 [==============================] - 0s 547us/step - loss: 0.2519 - accuracy: 0.9157
Epoch 181/200
13/13 [==============================] - 0s 654us/step - loss: 0.2633 - accuracy: 0.9036
Epoch 182/200
13/13 [==============================] - 0s 518us/step - loss: 0.2389 - accuracy: 0.9036
Epoch 183/200
13/13 [==============================] - 0s 637us/step - loss: 0.2390 - accuracy: 0.9197
Epoch 184/200
13/13 [==============================] - 0s 506us/step - loss: 0.2420 - accuracy: 0.9197
Epoch 185/200
13/13 [==============================] - 0s 553us/step - loss: 0.2606 - accuracy: 0.9157
Epoch 186/200
13/13 [==============================] - 0s 540us/step - loss: 0.2652 - accuracy: 0.9157
Epoch 187/200
13/13 [==============================] - 0s 597us/step - loss: 0.2483 - accuracy: 0.9116
Epoch 188/200
13/13 [==============================] - 0s 537us/step - loss: 0.2794 - accuracy: 0.9116
Epoch 189/200
13/13 [==============================] - 0s 563us/step - loss: 0.2628 - accuracy: 0.9157
Epoch 190/200
13/13 [==============================] - 0s 587us/step - loss: 0.2373 - accuracy: 0.9357
Epoch 191/200
13/13 [==============================] - 0s 531us/step - loss: 0.2378 - accuracy: 0.9277
Epoch 192/200
13/13 [==============================] - 0s 635us/step - loss: 0.2798 - accuracy: 0.9116
Epoch 193/200
13/13 [==============================] - 0s 524us/step - loss: 0.2877 - accuracy: 0.9157
Epoch 194/200
13/13 [==============================] - 0s 592us/step - loss: 0.2573 - accuracy: 0.9197
Epoch 195/200
13/13 [==============================] - 0s 550us/step - loss: 0.2601 - accuracy: 0.9157
Epoch 196/200
13/13 [==============================] - 0s 596us/step - loss: 0.2627 - accuracy: 0.9116
Epoch 197/200
13/13 [==============================] - 0s 537us/step - loss: 0.2515 - accuracy: 0.9197
Epoch 198/200
13/13 [==============================] - 0s 589us/step - loss: 0.2578 - accuracy: 0.9197
Epoch 199/200
13/13 [==============================] - 0s 586us/step - loss: 0.2257 - accuracy: 0.9277
Epoch 200/200
13/13 [==============================] - 0s 530us/step - loss: 0.2893 - accuracy: 0.9197

In [43]:
y_pred_class = model.predict(X_test_np)
y_pred_prob = model.predict(X_test_np)

In [44]:
print(y_pred_class)
print(y_pred_prob)

[[0.05459207]
 [0.76147234]
 [0.00915807]
 [0.03808615]
 [0.76147234]
 [0.01002619]
 [0.76147234]
 [0.01018906]
 [0.01153371]
 [0.01135194]
 [0.02130362]
 [0.26342314]
 [0.00895435]
 [0.06408602]
 [0.00861564]
 [0.38352323]
 [0.00858334]
 [0.00876492]
 [0.36599535]
 [0.00870827]
 [0.06301275]
 [0.00883013]
 [0.02832085]
 [0.6777434 ]
 [0.01030168]
 [0.40272492]
 [0.0098151 ]
 [0.709535  ]
 [0.00843859]
 [0.01017386]
 [0.01244307]
 [0.09117311]
 [0.00864956]
 [0.08251426]
 [0.02051628]
 [0.04260004]
 [0.24201971]
 [0.0996719 ]
 [0.05972281]
 [0.6322897 ]
 [0.00847554]
 [0.00939375]
 [0.00955355]
 [0.11677051]
 [0.01035178]
 [0.00904006]
 [0.02053136]
 [0.06636313]
 [0.7538283 ]
 [0.00981271]
 [0.00962377]
 [0.4325082 ]
 [0.6085234 ]
 [0.00883496]
 [0.00865665]
 [0.58219033]
 [0.01169831]
 [0.00951487]
 [0.00846416]
 [0.0226844 ]
 [0.09927449]
 [0.74169356]
 [0.01021579]
 [0.0167132 ]
 [0.07256749]
 [0.01680219]
 [0.01442122]
 [0.21403882]
 [0.01405135]
 [0.008499  ]
 [0.08531341]
 [0.59109646]
 [0.62283695]
 [0.00855231]
 [0.00857177]
 [0.69018906]
 [0.6667999 ]
 [0.3212372 ]
 [0.76147234]
 [0.21298176]
 [0.08357081]
 [0.00891665]
 [0.00925064]
 [0.76147234]
 [0.00849575]
 [0.6932864 ]
 [0.59826994]
 [0.01462215]
 [0.01009014]
 [0.01850095]
 [0.00859269]
 [0.47095236]
 [0.68558604]
 [0.01748946]
 [0.05095538]
 [0.00988677]
 [0.00971267]
 [0.01100436]
 [0.64019275]
 [0.59466916]
 [0.0386807 ]
 [0.008643  ]
 [0.02347925]
 [0.10076398]
 [0.00844088]
 [0.38805032]
 [0.5389211 ]
 [0.01730322]]
[[0.05459207]
 [0.76147234]
 [0.00915807]
 [0.03808615]
 [0.76147234]
 [0.01002619]
 [0.76147234]
 [0.01018906]
 [0.01153371]
 [0.01135194]
 [0.02130362]
 [0.26342314]
 [0.00895435]
 [0.06408602]
 [0.00861564]
 [0.38352323]
 [0.00858334]
 [0.00876492]
 [0.36599535]
 [0.00870827]
 [0.06301275]
 [0.00883013]
 [0.02832085]
 [0.6777434 ]
 [0.01030168]
 [0.40272492]
 [0.0098151 ]
 [0.709535  ]
 [0.00843859]
 [0.01017386]
 [0.01244307]
 [0.09117311]
 [0.00864956]
 [0.08251426]
 [0.02051628]
 [0.04260004]
 [0.24201971]
 [0.0996719 ]
 [0.05972281]
 [0.6322897 ]
 [0.00847554]
 [0.00939375]
 [0.00955355]
 [0.11677051]
 [0.01035178]
 [0.00904006]
 [0.02053136]
 [0.06636313]
 [0.7538283 ]
 [0.00981271]
 [0.00962377]
 [0.4325082 ]
 [0.6085234 ]
 [0.00883496]
 [0.00865665]
 [0.58219033]
 [0.01169831]
 [0.00951487]
 [0.00846416]
 [0.0226844 ]
 [0.09927449]
 [0.74169356]
 [0.01021579]
 [0.0167132 ]
 [0.07256749]
 [0.01680219]
 [0.01442122]
 [0.21403882]
 [0.01405135]
 [0.008499  ]
 [0.08531341]
 [0.59109646]
 [0.62283695]
 [0.00855231]
 [0.00857177]
 [0.69018906]
 [0.6667999 ]
 [0.3212372 ]
 [0.76147234]
 [0.21298176]
 [0.08357081]
 [0.00891665]
 [0.00925064]
 [0.76147234]
 [0.00849575]
 [0.6932864 ]
 [0.59826994]
 [0.01462215]
 [0.01009014]
 [0.01850095]
 [0.00859269]
 [0.47095236]
 [0.68558604]
 [0.01748946]
 [0.05095538]
 [0.00988677]
 [0.00971267]
 [0.01100436]
 [0.64019275]
 [0.59466916]
 [0.0386807 ]
 [0.008643  ]
 [0.02347925]
 [0.10076398]
 [0.00844088]
 [0.38805032]
 [0.5389211 ]
 [0.01730322]]

In [45]:
y_pred_class[:5]

array([[0.05459207],
       [0.76147234],
       [0.00915807],
       [0.03808615],
       [0.76147234]], dtype=float32)

In [46]:
y_pred_class = y_pred_class > 0.5
print(y_pred_class)

[[False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]]

In [47]:
print(y_pred_class.astype(int)[:5])

[[0]
 [1]
 [0]
 [0]
 [1]]

In [48]:
from sklearn.metrics import accuracy_score
res = accuracy_score(y_test_np, y_pred_class)
print(res)

0.8055555555555556

In [49]:
print(type(y_test))

<class 'pandas.core.series.Series'>

In [50]:
y_test.value_counts()

0    87
1    21
Name: Readmitted, dtype: int64

In [51]:
print(87/108)
print(21/108)

0.8055555555555556
0.19444444444444445

In [57]:
y_test.value_counts().head(1)/len(y_test)

0    0.805556
Name: Readmitted, dtype: float64